code in functions
#super function not working

## Load Libraries

In [52]:
import pandas as pd
import numpy as np
import zipfile
import matplotlib.pyplot as plt

## Load Data
- registrations
- courses
- students
- student_vle
- vle
- student_assessments
- assessments

In [53]:
zipfile_ou = '../../data/anonymisedData.zip'
#prediction_point = None

In [54]:


def load_data(zip_file_path):
    '''Loads the data from the Open University Learning Analytics dataset zip file.'''
    
    with zipfile.ZipFile(zip_file_path, 'r') as zip_file:
        registrations = pd.read_csv(zip_file.open('studentRegistration.csv'))
        courses = pd.read_csv(zip_file.open('courses.csv'))
        students = pd.read_csv(zip_file.open('studentInfo.csv'))
        student_vle = pd.read_csv(zip_file.open('studentVle.csv'))
        vle = pd.read_csv(zip_file.open('vle.csv'))
        student_assessments = pd.read_csv(zip_file.open('studentAssessment.csv'))
        assessments = pd.read_csv(zip_file.open('assessments.csv'))
    
    return registrations, courses, students, student_vle, vle, student_assessments, assessments

In [55]:
registrations, courses, students, student_vle, vle, student_assessments, assessments = load_data(zipfile_ou)

In [56]:
#reg_after_wd.head(20)

## 19 students withdrew on start date.

In [57]:
prediction_point = 150

## Clean and Add Student Information
- studentInfo
- registrations

In [58]:
def student_data(students, courses, registrations, prediction_point=None):
    '''Returns a dataframe of student data based on `students`: 

    prediction_point is an integer representing the number of days from the start of the course for which you want to predict the outcome.

    default is max(student_regist['module_presentation_length']) - that is, the last da of the lengthiest course

    - merge students and courses
    - merge registrations
    - drop missing value rows (date_registration, imd_band)
    - drop students who unregistered before registering
    - fills missing date_unregistration with module_presentation_length - that is, assumes they completed the course
    - removes students who withdrew or failed before prediction point
    '''

    # merge students and courses
    student_regist = pd.merge(students, courses, on=['code_module', 'code_presentation'], validate='many_to_one')

    # merge registrations
    student_regist = pd.merge(student_regist, registrations, on=['code_module', 'code_presentation', 'id_student'], how = 'left', validate='1:1')

    # drop missing value rows (date_registration, imd_band)
    student_regist.dropna(subset=['date_registration', 'imd_band'], inplace=True)

    # set default status to 'keep'
    student_regist['status'] = 'keep'

    # prediction point must be less than course length, integer, and greater than 0
    if prediction_point is not None:
        assert isinstance(prediction_point, int) and prediction_point > 0 and prediction_point <= (max(student_regist['module_presentation_length']) + 7), "Error: Invalid prediction point.\n\nPlease provide an integer value greater than 0 and less than or equal to the maximum course length.\n\nThis is the number of days from the start of the course for which you want to predict the outcome."
    
        # withdrawn or failed before prediction point - remove
        withdrawn_fail_condition = (student_regist['final_result'].isin(['Withdrawn', 'Fail'])) & (student_regist['date_unregistration'] <= prediction_point)
        student_regist.loc[withdrawn_fail_condition, 'status'] = 'remove_outcome_known'
    
        # unregister after prediction point - keep
        unregister_after_condition = student_regist['date_unregistration'] > prediction_point
        student_regist.loc[unregister_after_condition, 'status'] = 'keep'
    
        # if no unregistration date - keep
        no_unregistration_condition = student_regist['date_unregistration'].isna()
        student_regist.loc[no_unregistration_condition, 'status'] = 'keep'
    
        # query case
        student_regist.loc[~(withdrawn_fail_condition | unregister_after_condition | no_unregistration_condition), 'status'] = 'query'


    # rows which need investigation
    query_rows = student_regist[student_regist['status'] == 'query'] | student_regist[student_regist['status'].isna()]

    # print rows which need investigation
    if not query_rows.empty:
        print("The following rows need investigation.  They are excluded from the following analysis: \n")
        print(query_rows)
        student_regist = student_regist[~student_regist.isin(query_rows)].dropna()

    # replace missing date_unreg with module_presentation_length
    student_regist['date_unregistration'] = student_regist['date_unregistration'].fillna(student_regist['module_presentation_length'])

    # drop students who unregistered before starting
    student_regist = student_regist[student_regist['date_unregistration'] >= student_regist['date_registration']]

    # remove rows from final student df which are not needed
    model_final = student_regist[student_regist['status'] != 'remove_outcome_known']
   

    return model_final

In [59]:
model_final = student_data(students, courses, registrations, prediction_point)

In [60]:
model_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23122 entries, 0 to 32592
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   code_module                 23122 non-null  object
 1   code_presentation           23122 non-null  object
 2   id_student                  23122 non-null  int64
 3   gender                      23122 non-null  object
 4   region                      23122 non-null  object
 5   highest_education           23122 non-null  object
 6   imd_band                    23122 non-null  object
 7   age_band                    23122 non-null  object
 8   num_of_prev_attempts        23122 non-null  int64
 9   studied_credits             23122 non-null  int64
 10  disability                  23122 non-null  object
 11  final_result                23122 non-null  object
 12  module_presentation_length  23122 non-null  int64
 13  date_registration           23122 non-null  float64
 14  date_unregistration         23122 non-null  float64
 15  status                      23122 non-null  object
dtypes: float64(2), int64(4), object(10)
memory usage: 3.0+ MB

## Clean and Add Assessment Information
- assessmentInfo
- student assessments

In [61]:
def add_assessments(student_assessments, assessments, courses, model_final, prediction_point=None):
    '''Returns updated model_final dataframe with student assessment data added:

    prediction_point is an integer representing the number of days from the start of the course for which you want to predict the outcome.

    default is max(student_regist['module_presentation_length']) - that is, the last da of the lengthiest course

    - merge 'assessments' and 'courses' and 'student_assessments'
    - populate missing 'date' values with course final week - as suggested in literature
    - remove students from 'model_final' who have no score for an assessment
    - remove students with odd assessment dates (before registration, after unregistration, or very far into future)
    - remove students who withdrew or failed before prediction point
    - calculate new features - average score, submission date distance, proportion of assessments submitted
    '''
    # merge 'assessments' and 'courses' on 'code_module' and 'code_presentation'
    course_assess = pd.merge(assessments,courses, on=['code_module', 'code_presentation'], how='left')

    # fill in the missing 'date' values with course final week (as per literature)
    value_to_fill = course_assess['module_presentation_length'] - 3
    course_assess['date'] = course_assess['date'].fillna(value_to_fill)

    # merge student_assessments with course_assess
    stu_assess = pd.merge(student_assessments, course_assess, on=['id_assessment'], how='left')

    # drop no score for an assessment
    missing_score_rows = stu_assess[stu_assess['score'].isna()]

    if not missing_score_rows.empty:
        print("\n\nThe following students have missing 'scores'. Their are excluded from the analysis: \n")
        print(missing_score_rows)

        # drop rows with missing score
        stu_assess.dropna(subset=['score'], inplace=True)

    # remove students date_submitted values 21 days after course end date
    max_module_length = stu_assess['module_presentation_length'].max() +21
    
    stu_assess = stu_assess[stu_assess['date_submitted'] <= max_module_length]


    
    # if prediction_point is None
    if prediction_point is None:
        # no data reduction
        model_student_assess = stu_assess
        model_course_assess = course_assess
    else:
        # prediction point must be less than course length, integer, and greater than 0
        assert isinstance(prediction_point, int) and prediction_point > 0 and prediction_point <= (max(courses['module_presentation_length'])+7), "Error: Invalid prediction point.\n\nPlease provide an integer value greater than 0 and less than or equal to the maximum course length.\n\nThis is the number of days from the start of the course for which you want to predict the outcome."

        # reduce data by prediction point
        model_student_assess = stu_assess[stu_assess['date'] <= prediction_point]
        model_course_assess = course_assess[course_assess['date'] <= prediction_point]

    # expected assessment details
    expected_ass = model_course_assess.groupby(['code_module', 'code_presentation'])['id_assessment'].count().reset_index()
    expected_ass = expected_ass.rename(columns={'id_assessment': 'exp_sub_count'})
    date_sum = model_course_assess.groupby(['code_module', 'code_presentation'])['date'].sum().reset_index()
    expected_ass = expected_ass.merge(date_sum, on=['code_module', 'code_presentation'], how='left')
    expected_ass = expected_ass.rename(columns={'date': 'exp_sub_date_sum'})

    # summarise students' assessments by module_presentation
    student_assessment_summary = model_student_assess.groupby(['id_student', 'code_module', 'code_presentation']).agg(
        count_id_assessment=('id_assessment', 'count'),
        sum_score=('score', 'sum'),
        sum_date=('date', 'sum')
    ).reset_index()

    # merge student_assessment_summary and expected_ass on code_module and code_presentation
    merged_assess_summary = student_assessment_summary.merge(expected_ass, on=['code_module', 'code_presentation'])

    # calculate the new features
    merged_assess_summary['prop_submissions'] = merged_assess_summary['count_id_assessment'] / merged_assess_summary['exp_sub_count']
    merged_assess_summary['avg_score'] = merged_assess_summary['sum_score'] / merged_assess_summary['exp_sub_count']
    merged_assess_summary['submission_distance'] = merged_assess_summary['exp_sub_date_sum'] - merged_assess_summary['sum_date']

    # merge with 'model_final' - inner (loses no engagement students)
    #model_final = model_final.merge(merged_assess_summary, on=['id_student', 'code_module', 'code_presentation'], how='inner')

    # merge with 'model_final' - left (keeps students with no engagement - NaN need updating to 0 in tidy query)
    model_final = model_final.merge(merged_assess_summary, on=['id_student', 'code_module', 'code_presentation'], how='left')

  

    return model_final

In [62]:
model_final = add_assessments(student_assessments, assessments, courses, model_final, prediction_point)

The following students have missing 'scores'. Their are excluded from the analysis:

        id_assessment  id_student  date_submitted  is_banked  score  \
215              1752      721259              22          0    NaN
937              1754      260355             127          0    NaN
2364             1760     2606802             180          0    NaN
3358            14984      186780              77          0    NaN
3914            14984      531205              26          0    NaN
...               ...         ...             ...        ...    ...
148929          34903      582670             241          0    NaN
159251          37415      610738              87          0    NaN
166390          37427      631786             221          0    NaN
169725          37435      648110              62          0    NaN
170103          37435      480914              49          0    NaN

       code_module code_presentation assessment_type   date  weight  \
215            AAA             2013J             TMA   19.0    10.0
937            AAA             2013J             TMA  117.0    20.0
2364           AAA             2014J             TMA  117.0    20.0
3358           BBB             2013B             TMA   19.0     5.0
3914           BBB             2013B             TMA   19.0     5.0
...            ...               ...             ...    ...     ...
148929         FFF             2014J             TMA  199.0    25.0
159251         GGG             2013J             TMA   61.0     0.0
166390         GGG             2014B             TMA  166.0     0.0
169725         GGG             2014J             TMA   61.0     0.0
170103         GGG             2014J             TMA   61.0     0.0

        module_presentation_length
215                            268
937                            268
2364                           269
3358                           240
3914                           240
...                            ...
148929                         269
159251                         261
166390                         241
169725                         269
170103                         269

[173 rows x 11 columns]

In [63]:
model_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23122 entries, 0 to 23121
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   code_module                 23122 non-null  object
 1   code_presentation           23122 non-null  object
 2   id_student                  23122 non-null  int64
 3   gender                      23122 non-null  object
 4   region                      23122 non-null  object
 5   highest_education           23122 non-null  object
 6   imd_band                    23122 non-null  object
 7   age_band                    23122 non-null  object
 8   num_of_prev_attempts        23122 non-null  int64
 9   studied_credits             23122 non-null  int64
 10  disability                  23122 non-null  object
 11  final_result                23122 non-null  object
 12  module_presentation_length  23122 non-null  int64
 13  date_registration           23122 non-null  float64
 14  date_unregistration         23122 non-null  float64
 15  status                      23122 non-null  object
 16  count_id_assessment         21660 non-null  float64
 17  sum_score                   21660 non-null  float64
 18  sum_date                    21660 non-null  float64
 19  exp_sub_count               21660 non-null  float64
 20  exp_sub_date_sum            21660 non-null  float64
 21  prop_submissions            21660 non-null  float64
 22  avg_score                   21660 non-null  float64
 23  submission_distance         21660 non-null  float64
dtypes: float64(10), int64(4), object(10)
memory usage: 4.4+ MB

## Clean and Add VLE Information
- vleInfo
- student vle

In [64]:
def add_vle_data(model_final, student_vle, vle, courses, prediction_point=None):
    '''Returns updated model_final dataframe with vle data:

    prediction_point is an integer representing the number of days from the start of the course for which you want to predict the outcome.

    default is max(student_regist['module_presentation_length']) - that is, the last da of the lengthiest course

    - merge 'vle' and 'courses' and 'student_vle'
    - remove columns (week_from, week_to)
    - filter the rows where 'date' <= 'prediction_point'
    - create new features: vle_activity_count, student vle type count, student total clicks, student days active (engaged)
    
    '''
    # merge 'vle' and 'courses' on 'code_module' and 'code_presentation'
    course_vle = vle.merge(courses, on=['code_module', 'code_presentation'], how='left').drop(['week_from', 'week_to'], axis=1)

    # merge vle with student_vle
    all_stu_vle = pd.merge(student_vle, course_vle, on=['id_site', 'code_module', 'code_presentation'], how='left')

        
    # if prediction_point is None
    if prediction_point is None:
        # no filtering
        all_stu_vle = all_stu_vle
    else:
        # prediction point must be less than or equal to the maximum date
        assert isinstance(prediction_point, int) and prediction_point <= max(all_stu_vle['date']), "Error: Invalid prediction point.\n\nPlease provide an integer value less than or equal to the maximum date.\n\nThis is the cutoff date for filtering the rows."

        # filter the rows where 'date' <= 'prediction_point'
        all_stu_vle = all_stu_vle[all_stu_vle['date'] <= prediction_point]


    # filter the rows where 'date' is greater than 'module_presentation_length'
    vle_after_done = all_stu_vle[all_stu_vle['date'] > all_stu_vle['module_presentation_length']]

    if not vle_after_done.empty:
        print("The following rows need investigation. They are excluded from the following analysis: \n")
        print(vle_after_done)

        # match rows based on 'code_module', 'code_presentation', and 'id_student'
        matching_rows = model_final[model_final[['code_module', 'code_presentation', 'id_student']].isin(vle_after_done).all(axis=1)]

        # remove the matching rows from 'model_final'
        model_final = model_final[~model_final.index.isin(matching_rows.index)]

    # aggregations for each column
    aggregations = {
        'id_site': 'count',
        'activity_type': 'nunique',
        'sum_click': 'sum',
        'date': lambda x: x.nunique()
    }

    # group and apply the aggregations
    grouped_stu_vle = all_stu_vle.groupby(['code_module', 'code_presentation', 'id_student']).agg(aggregations).reset_index()

    # rename the columns
    grouped_stu_vle.rename(columns={
        'id_site': 'stu_activity_count',
        'activity_type': 'stu_activity_type_count',
        'sum_click': 'stu_total_clicks',
        'date': 'stu_days_active'
    }, inplace=True)

    # number of vle types per module_presentation
    group_vle = vle.groupby(['code_module', 'code_presentation'])['activity_type'].nunique().reset_index()
    group_vle.rename(columns={'activity_type': 'mod_pres_vle_type_count'}, inplace=True)

    # merge 'grouped_stu_vle' and 'group_vle' on 'code_module' and 'code_presentation'
    merged_vle_summary = grouped_stu_vle.merge(group_vle, on=['code_module', 'code_presentation'], how='left')

    # merge with 'model_final' - inner join - loses students without vle engagement
    #model_final = model_final.merge(merged_vle_summary, on=['id_student', 'code_module', 'code_presentation'], how='inner')

    # merge with 'model_final' - left join - keeps students without vle engagement, NaN nees updating to 0 in tidy function
    model_final = model_final.merge(merged_vle_summary, on=['id_student', 'code_module', 'code_presentation'], how='left')

    return model_final

In [65]:
model_final = add_vle_data(model_final, student_vle, vle, courses, prediction_point)

In [66]:
model_final.info()
#model_final.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23122 entries, 0 to 23121
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   code_module                 23122 non-null  object
 1   code_presentation           23122 non-null  object
 2   id_student                  23122 non-null  int64
 3   gender                      23122 non-null  object
 4   region                      23122 non-null  object
 5   highest_education           23122 non-null  object
 6   imd_band                    23122 non-null  object
 7   age_band                    23122 non-null  object
 8   num_of_prev_attempts        23122 non-null  int64
 9   studied_credits             23122 non-null  int64
 10  disability                  23122 non-null  object
 11  final_result                23122 non-null  object
 12  module_presentation_length  23122 non-null  int64
 13  date_registration           23122 non-null  float64
 14  date_unregistration         23122 non-null  float64
 15  status                      23122 non-null  object
 16  count_id_assessment         21660 non-null  float64
 17  sum_score                   21660 non-null  float64
 18  sum_date                    21660 non-null  float64
 19  exp_sub_count               21660 non-null  float64
 20  exp_sub_date_sum            21660 non-null  float64
 21  prop_submissions            21660 non-null  float64
 22  avg_score                   21660 non-null  float64
 23  submission_distance         21660 non-null  float64
 24  stu_activity_count          22708 non-null  float64
 25  stu_activity_type_count     22708 non-null  float64
 26  stu_total_clicks            22708 non-null  float64
 27  stu_days_active             22708 non-null  float64
 28  mod_pres_vle_type_count     22708 non-null  float64
dtypes: float64(15), int64(4), object(10)
memory usage: 5.3+ MB

In [67]:
# delete this cell - only for investigation.

# rows with NaN values
final_nan = model_final[model_final.isnull().any(axis=1)]
final_nan.head()

# columns with NaN values
columns_with_nan = model_final.columns[model_final.isnull().any()].tolist()

# Print the columns with NaN values
print("Columns with NaN values:", columns_with_nan)

#print(missing_count_assessment['id_student'].unique())

Columns with NaN values: ['count_id_assessment', 'sum_score', 'sum_date', 'exp_sub_count', 'exp_sub_date_sum', 'prop_submissions', 'avg_score', 'submission_distance', 'stu_activity_count', 'stu_activity_type_count', 'stu_total_clicks', 'stu_days_active', 'mod_pres_vle_type_count']

In [68]:
def tidy_up_model_final(model_final):
    '''Returns updated model_final dataframe:
    - deleted unnecessary columns
    - reordered columns
    - added subject, year, month columns
    
    '''
    # new columns for module_presentation - subject, year, month
    model_final['year'] = model_final['code_presentation'].str[:4].astype(int)
    model_final['month'] = model_final['code_presentation'].str[-1].map({'J': 'Oct', 'B': 'Feb'})

    # module subject mapping
    code_module_mapping = {
        'AAA': 'SocSci',
        'BBB': 'SocSci',
        'GGG': 'SocSci',
        'CCC': 'Stem',
        'DDD': 'Stem',
        'EEE': 'Stem',
        'FFF': 'Stem'
    }
    model_final['subject'] = model_final['code_module'].map(code_module_mapping)

    # rename 'module_presentation_length' to 'course_length'
    model_final.rename(columns={'module_presentation_length': 'course_length'}, inplace=True)

    # combine 'code_module', 'code_presentation', and 'id_student' into 'mod_pres_stu'
    #model_final['mod_pres_stu'] = model_final['code_module'] + '-' + model_final['code_presentation'] + '-' + model_final['id_student'].astype(str)

    # drop the separate columns 'code_module', 'code_presentation', and 'id_student'
    #model_final.drop(columns=['code_presentation'], inplace=True)

    # move 'final_result' to the last column
    final_result_column = model_final.pop('final_result')
    model_final['final_result'] = final_result_column

    # insert 'mod_pres_stu' as the first column
    #mod_pres_stu_column = model_final.pop('mod_pres_stu')
    #model_final.insert(0, 'mod_pres_stu', mod_pres_stu_column)

    # drop columns: 'count_id_assessment', 'sum_score', 'sum_date', 'exp_sub_count', 'exp_sub_date_sum'
    model_final.drop(columns=['count_id_assessment', 'sum_score', 'sum_date', 'exp_sub_count', 'exp_sub_date_sum', 'status'], inplace=True)
    
    # used for EDA - keeping student id
    #model_final.drop(columns=['count_id_assessment', 'sum_score', 'sum_date', 'exp_sub_count', 'exp_sub_date_sum'], inplace=True)

    # replace NaN values with 0 - these are students who did not engage (vle, assessment)
    model_final.fillna(0, inplace=True)

    # change year to categorical type
    model_final['year'] = model_final['year'].astype(str)

    return model_final

In [69]:
model_final = tidy_up_model_final(model_final)

In [70]:
model_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23122 entries, 0 to 23121
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   code_module              23122 non-null  object
 1   code_presentation        23122 non-null  object
 2   id_student               23122 non-null  int64
 3   gender                   23122 non-null  object
 4   region                   23122 non-null  object
 5   highest_education        23122 non-null  object
 6   imd_band                 23122 non-null  object
 7   age_band                 23122 non-null  object
 8   num_of_prev_attempts     23122 non-null  int64
 9   studied_credits          23122 non-null  int64
 10  disability               23122 non-null  object
 11  course_length            23122 non-null  int64
 12  date_registration        23122 non-null  float64
 13  date_unregistration      23122 non-null  float64
 14  prop_submissions         23122 non-null  float64
 15  avg_score                23122 non-null  float64
 16  submission_distance      23122 non-null  float64
 17  stu_activity_count       23122 non-null  float64
 18  stu_activity_type_count  23122 non-null  float64
 19  stu_total_clicks         23122 non-null  float64
 20  stu_days_active          23122 non-null  float64
 21  mod_pres_vle_type_count  23122 non-null  float64
 22  year                     23122 non-null  object
 23  month                    23122 non-null  object
 24  subject                  23122 non-null  object
 25  final_result             23122 non-null  object
dtypes: float64(10), int64(4), object(12)
memory usage: 4.8+ MB

In [71]:
model_final.head()

#duplicate_students = model_final[model_final.duplicated(subset='mod_pres_stu', keep=False)]['mod_pres_stu'].unique()

#duplicate_students

#missing_values = model_final.isnull().sum()
#print("Missing values:\n", missing_values, "\n")

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,...,submission_distance,stu_activity_count,stu_activity_type_count,stu_total_clicks,stu_days_active,mod_pres_vle_type_count,year,month,subject,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,0.0,133.0,6.0,710.0,29.0,9.0,2013,Oct,SocSci,Pass
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,0.0,313.0,7.0,1010.0,56.0,9.0,2013,Oct,SocSci,Pass
2,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,...,0.0,445.0,8.0,1499.0,83.0,9.0,2013,Oct,SocSci,Pass
3,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,...,0.0,242.0,7.0,825.0,50.0,9.0,2013,Oct,SocSci,Pass
4,AAA,2013J,38053,M,Wales,A Level or Equivalent,80-90%,35-55,0,60,...,0.0,404.0,7.0,1391.0,81.0,9.0,2013,Oct,SocSci,Pass

In [72]:
# Check for missing values in X_train_transformed
missing_values = model_final.isnull().sum()

# Filter rows with missing values
rows_with_missing = model_final[model_final.isnull().any(axis=1)]

# Save the rows with missing values to a separate DataFrame or file
rows_with_missing

Empty DataFrame
Columns: [code_module, code_presentation, id_student, gender, region, highest_education, imd_band, age_band, num_of_prev_attempts, studied_credits, disability, course_length, date_registration, date_unregistration, prop_submissions, avg_score, submission_distance, stu_activity_count, stu_activity_type_count, stu_total_clicks, stu_days_active, mod_pres_vle_type_count, year, month, subject, final_result]
Index: []

[0 rows x 26 columns]

In [73]:
model_final.to_csv('../../data/final_model_150_20230529.csv', index=False)

In [74]:
# not working

#def process_data(zip_file, prediction_point):
    # Load data from the zip file
    #registrations, courses, students, student_vle, vle, student_assessments, assessments = load_data(zip_file)

    # Process student data
   # model_final = student_data(students, courses, registrations, prediction_point)

    # Add assessments to model_final
   # model_final = add_assessments(model_final, student_assessments, assessments, courses, prediction_point)

    # Add VLE data to model_final
   # model_final = add_vle_data(model_final, student_vle, vle, courses, prediction_point)

    # Tidy up model_final
   # model_final = tidy_up_model_final(model_final)

  #  return model_final

In [75]:
# not working

#model_final = process_data(zipfile_ou, prediction_point)